x-commons: &default-settings
#  volumes:
#    - ${HOME}/.cache/huggingface:/root/.cache/huggingface
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: ["gpu"]
            driver: nvidia
            count: ${GPU_COUNT:-all}

services:
  # no model weights in light image
  chatllm:
    image: cyfeng/servllm:qwen2-1.5b-instruct
    shm_size: '16gb'
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # model name is required for light image
      #- SERVELLM_MODEL_NAME=Qwen/Qwen1.5-4B-Chat
      - SERVELLM_MODEL_DTYPE=auto
      - SERVELLM_MODEL_TP=1
    <<: *default-settings