services:
  build-n-push:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVELLM_MODEL_NAME: '${SERVELLM_MODEL_NAME:-Qwen/Qwen2-0.5B-Instruct}'
    image: 'cyfeng/servllm:${SERVELLM_TAG}'
